language: node_js
node_js:
  - '10'
sudo: required
services:
  - docker

before_install:
  - npm i

script:
  - npm run lint

after_success:
  - docker build -t bassemghoniem/rest-well .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bassemghoniem/rest-well

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "rest-well"
  env: "RestWell-env"
  bucket_name: "elasticbeanstalk-us-east-2-471358053311"
  bucket_path: "rest-well"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
